baseURL = 'http://matarillo.github.io/'
languageCode = 'ja-jp'
title = 'matarillo.github.io'
disableKinds = ["taxonomy", "term"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
      name = "Home"
      url = "/"
      weight = 1
  [[menu.main]]
      name = "dcsoup"
      url = "/dcsoup/"
      weight = 2
  [[menu.main]]
      name = "Word Brain"
      url = "/wordbrain/"
      weight = 3
  [[menu.main]]
      name = "MML Player"
      url = "/mmlplayer/"
      weight = 4
  [[menu.main]]
      name = "F# for Fun and Profit eBook"
      url = "/fsharp_for_fun_and_profit-ja/"
      weight = 5
